Comparision between Logistic, SVM , Decision and Random Forest

In [1]:
# Import package to load and hadle our data :
import pandas as pd
import numpy as np
from numpy import random

#  Import SK-Learn Library
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import accuracy_score

# Ignore warnings :
import warnings
warnings.filterwarnings('ignore')

Small example on kfold
https://towardsdatascience.com/train-test-split-and-cross-validation-in-python-80b61beca4b6


Cross Validation: we split our data into k subsets, and train on k-1 one of those subset. 
    What we do is to hold the last subset for test. We’re able to do it for each of the subsets.

In [2]:
%%html
<img src="kfold_flow.png" width=60%,height=50%>


In [3]:
list_data = [['logistic', 1], ['svc', 2], ['tree', 3],['forest',4],['linear',5],['Gaussian',6]]; 
df = pd.DataFrame(data=list_data,columns=['Algorithm','Label'])
df.head()

Algorithm  Label
0  logistic      1
1       svc      2
2      tree      3
3    forest      4
4    linear      5

In K-Folds Cross Validation we split our data into k different subsets (or folds). We use k-1 subsets to train our data and leave the last subset (or the last fold) as test data. We then average the model against each of the folds and then finalize our model. After that we test it against the test set.

In [4]:
k_fold = KFold(n_splits=5, shuffle=False, random_state=None)
for train_index, test_index in k_fold.split(df):
    print(train_index,test_index)

[2 3 4 5] [0 1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]


Above splitting of train and test split is done easily by cross fold validation akka cv

In [5]:
# So now we will load our data , already cleaned and encoded with labels
cleaned_bank_df = pd.read_csv('cleaned_bank_df.csv')
cleaned_bank_df.head()

job_0  job_1  job_2  job_3  marital_0  marital_1  marital_2  education_0  \
0      0      0      0      1          0          0          1            0   
1      0      0      0      1          0          0          1            0   
2      0      0      1      0          0          0          1            0   
3      0      0      1      1          0          0          1            0   
4      0      0      0      1          0          0          1            0   

   education_1  education_2   ...     poutcome_1  poutcome_2  age  balance  \
0            0            1   ...              0           1   59     2343   
1            0            1   ...              0           1   56       45   
2            0            1   ...              0           1   41     1270   
3            0            1   ...              0           1   55     2476   
4            1            0   ...              0           1   54      184   

   day  duration  campaign  pdays  previous  deposit  
0    5      1042         1     -1         0        1  
1    5      1467         1     -1         0        1  
2    5      1389         1     -1         0        1  
3    5       579         1     -1         0        1  
4    5       673         2     -1         0        1  

[5 rows x 35 columns]

In [6]:
#  Our Input Feature
X = cleaned_bank_df.iloc[:,:-1]
X.sample(5)

job_0  job_1  job_2  job_3  marital_0  marital_1  marital_2  \
400        0      1      0      0          0          1          0   
7714       0      0      0      1          0          1          1   
787        0      0      0      1          0          1          0   
10432      0      0      0      1          0          0          1   
3257       0      1      0      0          0          1          1   

       education_0  education_1  education_2    ...     poutcome_0  \
400              0            0            1    ...              0   
7714             0            1            0    ...              0   
787              0            1            0    ...              0   
10432            0            0            1    ...              0   
3257             0            1            0    ...              0   

       poutcome_1  poutcome_2  age  balance  day  duration  campaign  pdays  \
400             0           1   26      111    9       537         1     -1   
7714            0           1   32      787   11        72         2     -1   
787             0           1   37      455   13       904         6     -1   
10432           0           1   59     2552    5       125         3     -1   
3257            0           1   72      438   23       279         1     -1   

       previous  
400           0  
7714          0  
787           0  
10432         0  
3257          0  

[5 rows x 34 columns]

In [7]:
# Out output Label
y = cleaned_bank_df.iloc[:,-1]
y.sample(5)

7120    0
9815    0
8385    0
1442    1
7581    0
Name: deposit, dtype: int64

Comparison of Algos

In [8]:
# Output will show default parameters of svc
svc = SVC()
svc

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [9]:
model_lists = [LogisticRegression(),SVC(),tree.DecisionTreeClassifier(),RandomForestClassifier()]
score_lists = []
for ml in model_lists:
    score = cross_val_score(ml, X, y,cv=10)
    print(score.mean())
    score_lists.append(score.mean())

    

0.7762116896462059
0.5273240578729925
0.742357245928274
0.7683504577482436


So, above result shows LogisticRegression is best when we go for default conditions